### ISSUE TITLE
libpurpletorchat and Windows env var "PURPLEHOME"

### ISSUE THREAD

**Issue by geebotron** [prof7bit/TorChat#13]
libpurpletorchat doesn't seem to honor the env var "PURPLEHOME" which allows you to have your purple profile somewhere other than %APPDATA%
The user it creates is put in the %APPDATA% directory, not %PURPLEHOME%

**Comment by prof7bit** [comment]
yes, its currently using its own config folder (all the data that is not managed by libpurple itself (stuff that other protocols would store on their servers, like the authoritative buddy list, etc), its the same folder a standalone torchat client (based on the new code) would use.

But you are right, there might be scenarios where one would want all this inside the purple config folder. I will try to find a way to implement this.

**Comment by geebotron** [comment]
Thanks for your speedy response!

**Comment by revtowinark** [comment]
With PidginPortable from PortableApps, I tried to make the use of the Torchat plugin entirely portable.
Considering what is written in README.txt, I did set the %APPDATA% and the %PROGRAMFILES% environment variables in a batch file:
`set APPDATA=%CD%\Data\settings\.purple`
`set PROGRAMFILES=%CD%\ProgramF`
`PidginPortable.exe`

But the Torchat plugin seems not to recognize these environment variables.
The "torchat2_accountname" folder and purpletorchat.log are still stored in "C:\Documents and Settings\myaccount\Application Data" and tor.exe is still executed from "C:\Program Files\Tor".

**Comment by prof7bit** [comment]
I'm using the function SHGetSpecialFolderPath() (see the code in tc_config.pas) to get these paths, I am not directly reading environment variables. Its not yet possible to make a portable version of the plugin but its also not yet the final release version, its still alpha.

SHGetSpecialFolderPath() existed earlier and the %APPDATA% envionment variable was introduced in later versions of windows. I am not really sure why MS did not make SHGetSpecialFolderPath() respect the value of their new environment variables and therefore what the purpose of these new variables actually is since SHGetSpecialFolderPath() is still the only recommended way to get the path of these special folders.

I'm going to implement something to make it possible.

**Comment by prof7bit** [comment]
Ok, I'm going to implement the following in the next version:

for the base of the data directory search in the following order and use the first one that is found:
%PURPLEHOME%
%APPDATA%
SHGetSpecialFolderPath(CSIDL_APPDATA)

for tor.exe search the following and use the first one that is found:
%TOR_EXE%  (direct path to the exe file)
%PROGRAMFILES% (search the usual folders below that)
SHGetSpecialFolderPath(CSIDL_PROGRAM_FILES) (search the usual folders below that)

In later versions I will implement a configuration option for both that will take even higher precedence. 

For standalone portable torchat (not yet implemented) it will be a bit different, there it would not use %APPDATA% and %PROGRAMFILES% there will be a different algorithm to determine which folders to use.

**Comment by revtowinark** [comment]
Great news ! Thank you !

**Comment by prof7bit** [comment]
I'm closing this issue because I assume its fixed now. Please reopen if there are still problems.
