### ISSUE TITLE
TorChat to work wit Tor Browser Bundle under Windows HOW TO?

### ISSUE THREAD

**Issue by someuser** [prof7bit/TorChat#21]
Torchat runs it's own tor instance. 
How can i configure Torchat to work with already installed Tor Browser Bundle?

**Comment by prof7bit** [comment]
2012/9/3 someuser notifications@github.com

> Torchat runs it's own tor instance.
> How can i configure Torchat to work with already installed Tor Browser
> Bundle?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/prof7bit/TorChat/issues/21.

It not recommended in most situations because there is seldom any real need
for it.

You would first need to configure a hidden service in your already running
Tor (see the Tor documentation for this) and then in TorChat remove the
tor.exe file (the absence of tor.exe will make TorChat recognize that you
wish to run it with an existing tor proxy) and since it cannot on its own
detect the .onion name anymore when running in this mode you need to
configure the .onion name (the TorChat ID) that belongs to this hidden
service and the port numbers of the Tor proxy and the hidden service
manually.

It is all perfectly possible but its not recommended for beginners or
occasional users, there are just too many things that you might do wrong,
it needs a solid understanding of how hidden services are configured and
this is why I don't recommend it. Running its own tor.exe does not add any
significant resource usage onto the computer, even on very old computers
you will not notice any slowdown or notable RAM consumption, so this is why
by default it will start its own Tor process, its making everything much
simpler and more robust and I strongly recommend to leave it that way.
