### ISSUE TITLE
Force connect

### ISSUE THREAD

**Issue by panczypani** [prof7bit/TorChat#27]
I think it would be good to add in libpurple-torchat possibility to force connect to selected user without waiting, because sometime this time is very long.

```
==> torchatlogs/plugin.log <==
Dec 18 23:25:02.121 [M] <~/~~ (?P<username>.+) Socks4a connection failed: 91 (msg from thread xxx)
Dec 18 23:25:02.123 [M] (?P=username) next connect attempt in 582.[0-9]+ seconds (msg from thread xxx)
```

If is it hard add new options in GUI you can add it silently in "Get info" menu. I think it is good to add also in this window silently automatic ping (https://github.com/prof7bit/TorChat/pull/11).

For example about "Get info" menu:
- Gadu-Gadu (build-in Pidgin protocol) when I select ”Get info" Pidgin retrieving data from user directory Gad-Gadu network.
- IRC network (build-in Pidgin protocol) show parsed data from IRC received by command /whois

**Comment by prof7bit** [comment]
It is possible to implement this but I cannot really imagine any use case
where this should be necessary. Normally this means the other side is just
not reachable (contact is really offline). As soon as the other person
starts his torchat it will connect to you and send you a ping and as soon
as a ping is received the reconnect timer for this contact is reset to a
few seconds again.

The only scenario where this would not work where if for some really
strange reason _both_ sides have been trying to connect for a long time but
for some reason cannot reach each other. But if this really happens (I have
seen it happening sometimes) it usually never helps to just continue trying
again and again, the only thing that sometimes helps in such a situation is
to restart Tor and TorChat completely (and make sure no stale processes of
Tor.exe hanging around anymore) and/or hope that the other side will
eventually do the same.

Very often (in 90% of the cases) I have observed the reason for sudden
inability to connect a contact that has previously been working without
problems is that the contact has for some reason an old stale process of
Tor or TorChat still hanging around and the user is simply not aware of it
(because its only visible in task manager).

2012/12/18 panczypani notifications@github.com

**Comment by panczypani** [comment]
I think this can be useful when somebody have low quality network connection, but have static IP address. Maybe I'm wrong. 
nvmd 
Based on your answer, I found that I can disable and enable the account Torchat in Pidgin in this cases. In pyTorchat restart were easy, but in Pidgin when I am on couple IRC channel, have open a few conversation windows I can't turn off.

Thank you for this very useful software.
