### ISSUE TITLE
Client Mode no longer implemented?

### ISSUE THREAD

**Issue by knotwork** [prof7bit/TorChat#3]
It tries to copy tor.sh unconditionally to the user's .torchat/Tor directory, so dies if you delete tor.sh in the source/distribution directrory or copies it over again if you delete it i nthe user's directrory.

So the instructions on how to make it use your already running tor, and the [tor] section of config, seem to be out of date or the mode is no longer implemented or something?

**Comment by prof7bit** [comment]
You are right, this is a bug. I had made a little change in tor.sh and many users kept using the old tor.sh so I made it copy the new version every time. When I did this I simply did not think about the client mode, I just completely forgot it because I never used it myself. But the method of configuring something by removing a file was a dirty hack anyways. I will make it a regular config option in the next release. Meanwhile you can workaround it by simply commenting out the lines in config.py that copies the default tor.sh into the profile:

comment these two lines in config.py (by putting a # in front of them)
line 180 # shutil.copy(os.path.join("Tor", tor_exe), data_dir_tor 
line 189 # os.chmod(os.path.join(data_dir_tor, tor_exe), 0700)

Then delete tor.sh in your profile one more time and it should not ever recreate them again. In the next release I will have a proper solution for this.

**Comment by prof7bit** [comment]
fixed in 0.9.9.552
