### ISSUE TITLE
Torchat mustn't start a tor process

### ISSUE THREAD

**Issue by RoseDeSable** [prof7bit/TorChat#86]
Hi,
 I'm running tor as a service under my linux. Therefore I  doen't want, that the plugin restarts tor. What's to do ? 

Best Regards

**Comment by prof7bit** [comment]
It starts with different settings and different ports, it doesn't collide
with installed tor service. Just leave it that way, it will not cause any
problems, its the most pragmatic (and probably even the only) way to
approach this problem because the already running tor service can not be
dynamically reconfigured when starting TorChat.

Am Mo., 12. Nov. 2018 um 11:32 Uhr schrieb RoseDeSable <
notifications@github.com>:

**Comment by RoseDeSable** [comment]
Thanks.  If I correctly understand it, the plugin defines for each new tor-chat account in pidgin a new listener port 11007, 11006 .... and a new hostname.  I only have one account. In the debug of pidgin the plugin opens port 11008. I see a listening port for pidgin under 11009 but no 11008. Is that correct ? 

tcp        0      0 127.0.0.1:11009         0.0.0.0:*               LISTEN      ..../pidgin

**Comment by RoseDeSable** [comment]
Hi,
 I changed in src/core/tc_tor.pas the option "SocksListenAddress" in "SocksPort":

    //Line(Format('SocksListenAddress 127.0.0.1:%d', [FSocksPort]));
    Line(Format('SocksPort 127.0.0.1:%d', [FSocksPort]));
After re-compiling I see two tor-proccesses, where the one is hearing on Port 110008.

tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      .../tor
tcp        0      0 127.0.0.1:11008         0.0.0.0:*               LISTEN      .../tor

Tor's newer versions doen't seem to accept the option "SocksListenAddress" !

**Comment by prof7bit** [comment]
it really has been a very long time since I last looked at this code, I
also haven't followed the development of tor for about the same time, your
findings might be correct, I cannot remember it anymore from the top of my
head.

I would probably do a lot of the things different if I were to do it from
scratch again today, this also includes the choice of language for the
pidgin plugin, at the time I wrote this I wanted to prove the point that it
is "easy" to interface with the glib stuff from FPC when I was in my
"Pascal phase" but it is actually harder than doing it with C (I have since
become much more used to C due to my day job and would probably write the
plugin endirely in C). But I can't maintain this project any longer. I put
it on github in the hopes it would be useful and maybe someone will fork it
and give new life to it or just use the concept or only the protocol or the
idea behind it and make a modern version of it from scratch. But I
personally cannot at the moment find enoug motivation (and time) to take it
up and continue again.


Am Mo., 12. Nov. 2018 um 15:51 Uhr schrieb RoseDeSable <
notifications@github.com>:

**Comment by RoseDeSable** [comment]
Yes,
 something would be to do. Because of security reasons some users aren't running as administrator (root), for example to make it more difficultly to install a terrible maleware. Therefore they can't start a tor-process. So it must exist an option for changing the mode for dynamic to static. In the static mode the tor service must have so much hidden services for torchat, how the user has  torchat-accounts in pidgin. And Pascal. Yesterday I must install the compiler for Pascal for running "make". Because C is more used in linux programs of such kind like tor, I also would completly write the  plugin in this language. A good luck for finding programmers for your project. 

Best Regards
